### ISSUE TITLE
Database does not contain 'letterhints' in feild lists. 

### ISSUE THREAD

**Issue by LuciaLiljegren** [marcusgreen/moodle-qtype_gapfill#105]
I don't know if this is a bug. But 

**Debug info: Unknown column 'letterhints' in 'field list'**
Several problems (1) There is no "uninstall" button next to Gapfil.
Any attempt to load a gapfil question throws the same error. I will describe ONE process

**To Reproduce**
1. Visit https://www.XXX.com/moodle/question/bank/managecategories/category.php?courseid=29
2. Click on 'any category that contains a gapfill questoin'
4. This is the error:

"Error reading from database

[More information about this error](http://docs.moodle.org/400/en/error/moodle/dmlreadexception)
Debug info: Unknown column 'letterhints' in 'field list'
SELECT answerdisplay, delimitchars, casesensitive, noduplicates, disableregex, fixedgapsize, optionsaftertext, letterhints, singleuse FROM mdl_XX_question_gapfill WHERE question = ?
[array (
0 => '19704',
)]
Error code: dmlreadexception"

**Expected behavior**
Should display the questions in the category, along with "create new question" and so on.

These are my versions. 

**Screenshots**

**Additional context**
The  mdl_XX_question_gap fill IS missing "letterhints"
The problem started a while ago. I was negligent-- but in the past the questions appeared in in categories and questions, and only threw errros if I tried to use them. So many are binned in categories called "broken". (I was going to get around to fixing.)

I'm hoping I can either just depete everything about the plugin (I'll lose some questions.) OR better, I can access the questoins. (I can add a column to the database if that's the fix. But I need to know the properties. Integer? etc.)

![image](https://github.com/marcusgreen/moodle-qtype_gapfill/assets/140638964/f91e9517-645c-486e-864f-a44e77489bc6)

**Comment by catalyst-marcus-green** [comment]
Hi LuciaLiljegren,
Did you solve this. If you need further help email me directly at marcusavgreen at gmail.com

**Comment by LuciaLiljegren** [comment]
I haven't. I emailed! Thanks!
Lucia

**Comment by marcusgreen** [comment]
Closing ticket as this issue has been addressed in version 2.138. Many thanks to Lucia for reporting this
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
