### ISSUE TITLE
Drag & Drop not working

### ISSUE THREAD

**Issue by VinBot50** [marcusgreen/moodle-qtype_gapfill#107]
**Describe the bug**
The Drag & Drop option of the Gapfill type question in Moodle(4.2) does not work at all. I can type the answers into the provided spaces but it won't let me "pick up" an answer and place it in the spaces.

Create a Quiz in Moodle, add a Gapfill question, select Drag & Drop.
Drop Down and Gapfill options work fine, but Drag & Drop doesn't.

**Desktop (please complete the following information):**
 - OS: Android & iOS
 - Browser: Chrome, Safari
 - Version: All versions

**Comment by marcusgreen** [comment]
Could you supply more information about your Moodle setup. What what 3rd party plugins do you have, and in particular what theme do you have installed, and does the same problem show up without that theme.


An easy way to find that out is to to your moodle install and add this to the root.
/admin/plugins.php?updatesonly=0&contribonly=1
These statistics 
https://moodle.org/plugins/qtype_gapfill/stats
Suggest that at least 386 Moodle sites have Gapfill installed with Moodle 4.2
Though that says nothing about the client os being used.

Can you confirm this is with a web browser on those two mobile platform and not in the mobile app.

Also can you give me a student access to a course on your site with a quiz containing an example question.

**Comment by VinBot50** [comment]
Hi Marcus

Thanks for your prompt response, but it seems I may have jumped the gun a bit with this, after retesting the Drag & Drop option on another device, it appears that it does work on newer versions of Android, however, it still does not work on the older versions(OS 5 and older) basically those that cannot be updated anymore, as Chrome no longer supports them. I think that may have more to do with Chrome being outdated, rather than an issue with the plugin.
The iOS devices have the same problem, they are just too old to support updated versions of Chrome or Safari.

I apologise for the post, I should have investigated a little more before posting here.

**Comment by marcusgreen** [comment]
That is wonderful to hear.

I always like to mention anyone who asks questions or gives me information in the updates log, here
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
Can I mention you raised a ticket and if so what name would you like me to use.

Drag and drop can be quite a complex thing to program and if I had the time I would like an option to click to select and then click to drop (or similar). In my view Drag and drop is not the best way of doing things on a small interface.

The question type comes with a set of example questions that people can find useful
https://github.com/marcusgreen/moodle-qtype_gapfill/tree/master/examples/en

Best wishes
Marcus

**Comment by VinBot50** [comment]
You are welcome to mention me, you can use my actual name: Gavin, from South Africa, if you'd like to add that as well.

I agree with you that tapping to select and then tapping to drop would be a better option, iOS used to have it about 7 years ago in Safari, but I noticed that they also do the drag and release now.

Thank you for the examples, they may come in handy when training the teachers here at the school, the more examples I have to show them the better.

All the best to you
Gavin

**Comment by marcusgreen** [comment]
Thank you
If you like Gapfill you might like its beautiful sister Wordselect.
https://moodle.org/plugins/qtype_wordselect

**Comment by VinBot50** [comment]
Thank you it looks interesting, our foundation phase teachers should be able to make use of it.
