### ISSUE TITLE
Per gap feedback

### ISSUE THREAD

**Issue by mister-mori** [marcusgreen/moodle-qtype_gapfill#108]
**Describe the bug**
Hello. I have noticed strange behaviour with per gap feedback. I am not really sure if it's a bug.

When I enter the answers and then press the "Check" button I can see which answers are right or wrong. But I cannot see any per gap feedback (screenshot 1).

I can only see per gap feedback after pressing the "Finish attempt button" (screenshot 2). When I have a lot of exercises in a quiz I would like my students to check their answers before doing the next exercises so they can do "self-correction" and gain some confidence that they are doing well. There are questions in exercises in which 90% of students make the same mistake and they need a clue in order to understand and solve it.

**Expected behavior**
But when I try the same with the Embedded answers (Cloze) question I can see which answers are right or wrong and I can see per gap feedback as well before pressing the "Finish attempt button. (screenshot 3).

I don't know which Moodle version it is, but as Marcus's video implies when the "Check" button is pressed the per gap feedback reveals. https://www.youtube.com/watch?v=QgmAwR-Wa6Y&ab_channel=marcusavgreen

**Video**
https://www.youtube.com/watch?v=uMUe7Yv9_KE

**Screenshots**
Screenshot 1
![Screenshot_1](https://github.com/marcusgreen/moodle-qtype_gapfill/assets/84474875/b5e939e4-9b6a-4817-a25d-2dd9b91a16e1)
Screenshot 2
![Screenshot_2](https://github.com/marcusgreen/moodle-qtype_gapfill/assets/84474875/ef1e22ed-bff4-4e71-9d8a-95db8f3247d8)
Screenshot 3
![Screenshot_3](https://github.com/marcusgreen/moodle-qtype_gapfill/assets/84474875/89822104-33a2-4aa6-867b-0a314dd61f02)

Moodle xml
[questions-PLA1-Embedded (gapfill test)-20231019-1915.txt](https://github.com/marcusgreen/moodle-qtype_gapfill/files/13045048/questions-PLA1-Embedded.gapfill.test.-20231019-1915.txt)
[questions-PLA1-Gapfill (feedback test)-20231019-1915.txt](https://github.com/marcusgreen/moodle-qtype_gapfill/files/13045049/questions-PLA1-Gapfill.feedback.test.-20231019-1915.txt)

**Comment by marcusgreen** [comment]
Yes, it is behaving as designed. I would like to have per-gap hints/multiple attempts feedback but it would require significant additional programming. At some point I will need to make the per-gap code work with TinyMCE. I have a little experience with TinyMCE but it will still take quite a bit of time. Pleased to see you are exploring the features.
