### ISSUE TITLE
DDL sql execution error  while Upgrading moodle from 2.5 to 2.6

### ISSUE THREAD

**Issue by krishreddy** [marcusgreen/moodle-qtype_gapfill#15]
Hi ,when i am going to upgrade my moodle version from 2.5 to 2.6 i got the errors in my chrome browser  " DDL sql execution error  "

It is usually not possible to recover from errors triggered during installation, you may need to create a new database or use a different database prefix if you want to retry the installation.

Can anyone  explain why i get this error and where i can do the changes in my code.

**Comment by marcusgreen** [comment]
You would be better asking general questions about upgrading Moodle itself in the forums at Moodle.org. However a couple of tips are to turn the level of debugging to "developer", see the admin menu, and then ask a question in the forums that includes as much information as possible, i.e. database type and version, PHP version, operating system etc (more information is better). Good luck
