### ISSUE TITLE
Exponents do not work 

### ISSUE THREAD

**Issue by ccahillmn** [marcusgreen/moodle-qtype_gapfill#19]
I have tried creating gapfill questions with exponents as both the correct answer ("the gap") and the distractors using the html superscipt tag and LaTex math; neither method works. Here is what happens to the values with each:

# HTML Superscript
![exponents-superscript](https://cloud.githubusercontent.com/assets/5407530/18560889/18a23500-7b43-11e6-9243-c6edc1e46f7f.png)

The correct answer from the question text displays correctly, but gets messed up when dragged into the input. The distractors display as whole numbers.

# LaTex Math
![exponents - latex](https://cloud.githubusercontent.com/assets/5407530/18560938/55ad3bf2-7b43-11e6-95a9-ef0518b12b74.png)

Using LaTex, the correct answer displays correctly, but gets messed up when dragged into the input, though different than with html superscipt. The distractors display as raw LaTex.

# Example
Those were just dummy text I was testing with. Here are screenshots of an actual question from a teacher using superscripts.
![gapfill1](https://cloud.githubusercontent.com/assets/5407530/18561039/bfb6b780-7b43-11e6-95dd-a1c758580aa6.png)
![gapfill2](https://cloud.githubusercontent.com/assets/5407530/18561052/d056431c-7b43-11e6-83f1-8ab15ea1f2b1.png)

**Comment by marcusgreen** [comment]
HI, I'm not sure Gapfill is the right question type for this, formula or equation might be better (though it is a year or so since I have experimented with them). Gapfill will only work with characters that will display in a standard HTML form. This means it will not render any html or latex. You might be able to do this with unicode characters. Here is an example I just created.
![image](https://cloud.githubusercontent.com/assets/732202/18569293/9816f81a-7b99-11e6-9d15-da1465887d43.png)

**Comment by marcusgreen** [comment]
Here is the source for that
What is ten to the power 3?[10³]<br>

What is ten to the power 4?[10⁴]<br>

What is ten to the power 5?[10⁵] <br>

What is ten to the power 6?[10⁶]<br>

What is ten to the power 7?[10⁷]<br>

What is ten to the power 8?[10⁸ ]<br>

What is ten to the power 9?[10⁹]<br>

**Comment by ccahillmn** [comment]
Thank you for your quick response - I will pass this along to my teachers. They absolutely love gapfill as a quick and easy way to differentiate questions for varying abilities. Your work on this is appreciated.

**Comment by marcusgreen** [comment]
Many thanks for your feedback. It was your question that motivated me to find those extended characters so it is appreciated. I will close the query now.
