### ISSUE TITLE
Surplus space before closing square bracket causes an error.

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marcusgreen/moodle-qtype_gapfill#20]
Hi Marcus,
I was attempting to reproduce a Spanish version of the image at https://docs.moodle.org/31/en/File:tenpower.png , using the text you had in https://docs.moodle.org/31/en/Gapfill_question_type#Extended_Characters. 

I obviously copied and pasted "What is ten to the power 8?[10⁸ ]" (notice the extra space before the closing square bracket.

I was using a 3.1.1 Moodle in Spanish in a local server and I got an error (screen attached). Can you please confirm this error caused by surplus space before I add it in in the documentation page? 

Thanks in advance.

![es_tenpower_error](https://cloud.githubusercontent.com/assets/2671923/18719208/067fa68e-7fec-11e6-9f48-2d03658c1712.png)

**Comment by marcusgreen** [comment]
Thanks for the feedback German, I will look into that.

**Comment by marcusgreen** [comment]
On reflection, I think it is supposed to work like that, as the question type is designed to allow strings with spaces and I think it will allow spaces at the start and end. I will take a look at the code.

**Comment by germanvaleroelizondo** [comment]
Closing this issue now.
