### ISSUE TITLE
No English language strings in AMOS for Moodle 3.1

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marcusgreen/moodle-qtype_gapfill#21]
Hi Marcus,
AMOS currently does not host the English language strings for translating (all languages) your Gapfill plugin for Moodle 3.1, while branches from 2.1 to 3.0 are OK.

Please have a look at the developer's documentation at https://docs.moodle.org/dev/Translating_plugins#If_translations_are_available_in_AMOS_for_some_Moodle_branches_but_not_available_for_other_branches.

Your gapfill plugin is great. I will be looking forward to having it translatable in Moodle 3.1.

**Comment by marcusgreen** [comment]
I suspect it is the string concatenation in the line
$string['courseshortname_help'] . Does that sound likely?

**Comment by germanvaleroelizondo** [comment]
Indeed. String concatenation is not allowed by AMOS processing. Can you please change it? THANKS.

**Comment by marcusgreen** [comment]
I shall investigate doing a point release as I have just seen an opportunity for a fix for something else as well.

**Comment by germanvaleroelizondo** [comment]
Still no progress in this issue :(

**Comment by marcusgreen** [comment]
Thanks for reminding me, I will get on with the job.

**Comment by germanvaleroelizondo** [comment]
I will be looking forward to your new version :)

**Comment by germanvaleroelizondo** [comment]
AMOS now has all Moodle branches available for translation. 
THANKS :)
