### ISSUE TITLE
Spaces in distractors break review with drop-down selected

### ISSUE THREAD

**Issue by thepurpleblob** [marcusgreen/moodle-qtype_gapfill#24]
To reproduce...
- Create a simple gapfill with Question text something like "Enter your answer [123]".
- Enter, distractors with spaces after the commas, e.g. "456, 789, 345, 567".
- Select "dropdown" for "Display answers" setting. 
- Save

Log in as a student and attempt the quiz. Select a wrong answer from the question. Save and review. 

The question is correctly marked as wrong, but the answer "box" is completely empty. Looking at the generated HTML the <select> is correct but there is no 'selected' next to the chosen answer. 

When drag-and-drop is selected instead it works perfectly.

Looks like the spaces are getting trimmed in one place but not in the other...

**Comment by marcusgreen** [comment]
Added fix into V1.92, see "deal with spaces in wronganswers" comment on questiontype.php
