### ISSUE TITLE
Locale issue with numbers only

### ISSUE THREAD

**Issue by mcardle** [marcusgreen/moodle-qtype_gapfill#25]
I Denmark we use a dot "." as the thousands separator and a comma for the fractional part of the number. 

This is a problem for the teachers, if they have math questions with numbers only.

**English:**&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**Danish:**
0.001&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0,001
0.01&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0,01
0.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;0,1
1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1
10&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10
100&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;100
1,000&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.000
10,000&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10.000
100,000&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;100.000
1,000,000&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.000.000

1.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1,00
10.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;10,00
100.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;100,00
1,000.00&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1.000,00

And so on...

Question text
![question-text](https://cloud.githubusercontent.com/assets/4198807/22145743/ef0786cc-df02-11e6-98dd-1c2af7d321c0.png)

Answers
![answers](https://cloud.githubusercontent.com/assets/4198807/22145744/ef07d4ce-df02-11e6-9380-34973c06a5a8.png)

Fill in correct responses
![fill-in-correct-responses](https://cloud.githubusercontent.com/assets/4198807/22145742/ef06f27a-df02-11e6-9305-256df7c9018b.png)

As you can see on the screenshots, the answers are correct, when they are filled, but the answers are missing.

I really hope you would consider releasing a patch for this issue in the near future. By the way - you do an awesome job on this plugin, keep up the good work.

Best regards Ulrik McArdle

**Comment by marcusgreen** [comment]
Not only Denmark, can you email the source of your question (view and copy the html). Email to marcusavgreen@gmail.com

**Comment by marcusgreen** [comment]
No need to do that, I have reproduced what your illustration shows.

**Comment by mcardle** [comment]
Okay, thank you for looking into it...

**Comment by marcusgreen** [comment]
Hi Ulrik, I appreciate your feedback on this, I had not seen this issue previously 

If you go to 

http://questiontype.co.uk/mdl
And scroll to the bottom of the course list
You will see Gapfill Question Type Demonstration Course
Can you login to that with the credentials
username
student
password
test

You should see a single question quiz called For Ulrik
Please experiment with that to confirm it behaves as you would expect. If that does address the issue I will need to run the automated tests and do other testing before it is ready to be put into the live version. I am currently on a development cycle that plans for an update of the question type in the near future.

Let me know when you have looked at that single question quiz and I will then remove it from the course.

Best wishes
Marcus

**Comment by mcardle** [comment]
Hi Marcus...

It looks like its working like it should. How did you do the comparison - did you force the type to be string? I think it would work like that.

// Ulrik

**Comment by marcusgreen** [comment]
You can see a diff here
https://github.com/marcusgreen/moodle-qtype_gapfill/commit/7747cb20e53148a37bda3fd34aa48655b81a89d8#diff-43c4c525ee05e2967e5508db573b6f68

On line 132 I added true to the end of in_array function call.

When I get an opportunity I will run the unit tests which has about 180 checks in it which should confirm it has not broken anything.

Do you use this question type for English language teaching by any chance? Email me at marcusavgreen at gmail.com.

**Comment by mcardle** [comment]
Okay... So it is strict type matching in the array. I am looking forward to see the result of the tests :)

Thanks again.

**Comment by marcusgreen** [comment]
I have run the standard tests and it didn't break any of them. I will test further to be confident.

**Comment by mcardle** [comment]
Sounds great.

**Comment by marcusgreen** [comment]
Version 1.93 which is in the plugins database includes this fix.
