### ISSUE TITLE
GapFill Install requires an earlier Moodle

### ISSUE THREAD

**Issue by demsley** [marcusgreen/moodle-qtype_gapfill#26]
When installing from https://moodle.org/plugins/view.php?plugin=qtype_gapfill I get the message:  

Status 	Message 	Info
OK 	Name of the plugin to be installed  gapfill

OK 	Plugin version 2017022200

Error 	Required Moodle version 	2015051109

My version of Moodle is: Moodle 2.9.8+ (Build: 20160915)

Any clues please?

Cheers

Dave

**Comment by marcusgreen** [comment]
Hi DaveI
Sorry about the delay in getting back to you, I am not sure why you are getting that error, it looks like it ought to install without a problem and I have checked that it is not to do with the number of digits in the string. If you contact me directly via email at marcusavgreen at gmail dot com I will see what can be done

**Comment by marcusgreen** [comment]
Hi Dave
Did you manage to solve this?

**Comment by germanvaleroelizondo** [comment]
I just tested a server (Moodle 2.9.9+ (Build: 20161129) with gapfill version 2017022200 and it works beautifully :)

A Moodle 2.9.8+ should be easy to upgrade to 2.9 (at least).

Maybe this issue should be closed

**Comment by webpedagogy** [comment]
Hello, this issue occurred with me today. Upgrading from ver 2006082518 on Moodle 2.9 (Build: 20150511). I am stuck in an upgrade loop that I cannot get out of. Please help ASAP!

By the time the red flag came up regarding the Moodle version required I could not go back.

**Comment by marcusgreen** [comment]
I am looking into it.

**Comment by marcusgreen** [comment]
Have you tried upgrading to this version first?
https://moodle.org/plugins/pluginversion.php?id=14350
Do you have access to the files on your server?
You can contact me directly at marcusavgreen at gmail dot com which may get you a quicker response

**Comment by webpedagogy** [comment]
Thanks Marcus, I'm trying to roll back to the previous version atm.

Will this work? ... delete all files in the /question/type/gapfill folder,
then use the plugin installer interface to upload the ealier version
(qtype_gapfill_moodle31_2006082518.zip)? We have lots of existing instances
of the gapfill question in our current site - Moodle 2.9 (Build: 20150511)
so I'm keen to roll back if I can.

**Comment by marcusgreen** [comment]
You can find me on skype as marcusgreen if you want a voice chat. I am fairly confident that what you describe will not work.

**Comment by marcusgreen** [comment]
It will probably complain that you are trying to downgrade the versions.

**Comment by marcusgreen** [comment]
Or the google hangout chat on that email address I gave earlier in this thread

**Comment by marcusgreen** [comment]
I believe this was solved. If not feel free to re-open.
