### ISSUE TITLE
Gapfill question not closing .que div tag

### ISSUE THREAD

**Issue by ccahillmn** [marcusgreen/moodle-qtype_gapfill#27]
With the default settings, a Gapfill .que div does not have a closing tag. If you enable the setting "Options after text", the div closes correctly. This is especially apparent when using relative (em) font sizing such as with the Boost theme, as each question gets progressively larger.

I fixed this by adding
`else{
            $questiontext .= "</div>";
}`
at line 79 on renderer.php

**Comment by marcusgreen** [comment]
Thanks for the feedback, could you email me at marcusavgreen at gmail.com, I have a question to ask.

**Comment by marcusgreen** [comment]
I think that updates since have fixed, this. If I am not correct, re-open, re-create or email me.
