### ISSUE TITLE
The texts for the sample questions are not translatable in AMOS

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marcusgreen/moodle-qtype_gapfill#28]
As described in https://moodle.org/mod/forum/discuss.php?d=359258 , the text currently used for the included sample questions would be very important, but also very cumbersome, for mere Moodle translators (such as myself), to translate into other languages.

Declaring the text as string variables for the plugin will allow all AMOS translators to easily and quickly translate these example questions into languages other than English.

While this is a suggested improvement, I think it should not be particularly difficult, nor time-consuming, for a skilled Moodle programmer, such as Marcus Green :)

**Comment by germanvaleroelizondo** [comment]
Any progress ?

**Comment by marcusgreen** [comment]
I have added the text for three sample questions to the strings starting with 
example1
And created a folder structure under examples for the different languages. This is not perfect but it is a start.

**Comment by germanvaleroelizondo** [comment]
This is good progress.

Congratulations Marcus.

I have made a pull request for fixing untranslated strings in the Spanish example. 

I tested the original XML file (I got English feedback) and the new one (I got Spanish feedback).

But ideally, maybe it would be even better if the newly used strings were declared as string variables and therefore available for translation in AMOS. Would that be too complicated and time-consuming to program?

**Comment by germanvaleroelizondo** [comment]
I have translated the above sentences :)

$string['example1'] = 'Arrastre los verbos hacia los huecos. Él se [rió] y se [sentó]';
$string['distractor1'] = 'azul,zapato,chico';
$string['example2'] = 'Seleccione los verbos de los menús desplegables. Él se [rió] y se [sentó]';
$string['distractor2'] = 'azul,zapato,chico';
$string['example3'] = '¿De donde proviene el canguro? [Australia]. El hueco siguiente aceptará, ya sea, gato o perro [gato|perro]';

**Comment by germanvaleroelizondo** [comment]
BUT,
Shouldn't the string variables be declared insidethe  /lang/en/qtype_gapfill.php file ?
So, that they will be available for translation in AMOS ?

**Comment by marcusgreen** [comment]
Yes, you should be able to see the English versions at the end of that file

**Comment by germanvaleroelizondo** [comment]
When will you upload the new plugin version to the Moodle plugins database?

I do not recall having seen the new strings availabe for translation yet.

**Comment by marcusgreen** [comment]
I have just had a look in amos for Moodle 3.5 and gapfill picked spanish and scrolled down to the string names starting with E.
It has 3.5 | example2 | qtype_gapfill waiting for your lovely translation ....

**Comment by germanvaleroelizondo** [comment]
Your gapfill plugin is CURRENTLY translated into 18 languages in AMOS:

Basque (eu),  Catalan (ca), Catalan (Valencian) (ca_valencia) , Chinese (Traditional/Big5) (zh_tw) , Croatian (hr) , Czech (cs), Dansk (da),  French (fr) , German (de) , Hebrew (he) ,  Mongolian (mn) , Norwegian (no) , Portuguese (Brazil) (pt_br), Português (pt) , Romanian (ro), Slovenian (sl) , Spanish (International) (es) , Spanish - Mexico (es_mx) 

:1st_place_medal:

**Comment by germanvaleroelizondo** [comment]
Sorry Marcus,
Am I missing something?

I just checked AMOS:

There are 70 strings for qtype_gapfill, and all of them have been translated into Mexican Spanish. Only 20 have been translated for International Spanish.

I will send the 50 remaining translations to the guys in Spain in half an hour.

**Comment by germanvaleroelizondo** [comment]
I have submitted the international Spanish translations. They usually take 1 to 3 weeks for processing them.

**Comment by marcusgreen** [comment]
That is excellent. I was trying to find out which languages it is translated into recently but I could not work out how. I think it is me that is missing something, mainly more of an understanding of Amos.

**Comment by germanvaleroelizondo** [comment]
AMOS settings:

Select all languages
select component qtype_gapfill
version 3.5
select only translated strings
stringidentifier pluginname

should do the trick

**Comment by germanvaleroelizondo** [comment]
By the way,

Did you know that you can also add a translation for es_kids (and ja_kids and es_mx_kids) language packs ?

With these language packs, children get a simplified version of some Moodle strings.
