### ISSUE TITLE
support for images

### ISSUE THREAD

**Issue by chetsmith** [marcusgreen/moodle-qtype_gapfill#29]
Hello, 

Is it possible to use an image in the gap fill question type? issue #14 references it is something that has been discussed. If it is not, is it something you're considering?

**Comment by marcusgreen** [comment]
Hi Chet
You can use images within the form in the sense of decoration or things in a table
but you cannot use it as the thing that you drag or the target you drag to.
https://docs.moodle.org/31/en/Gapfill_question_type#Tables_with_images

Core Moodle includes some question types that allow manipulation of images, 
The best combination of usability and feature in my opinion is ddmarker, the 
other one is a bit awkward to use. I have thought about creating some sort of question type that allows images, but in an easy to use manner but I have no current plans to do so.

The next release of gapfill will include the feature shown in this video
https://www.youtube.com/watch?v=AWqmLycZyvo&feature=youtu.be
