### ISSUE TITLE
Can it be translated?

### ISSUE THREAD

**Issue by dinism** [marcusgreen/moodle-qtype_gapfill#30]
I'm a Portuguese (PT) translator.
# In site administration / plugins
![imagem](https://user-images.githubusercontent.com/14828021/35508750-6f45591a-04e9-11e8-81b6-edbe0e04c170.png)
# When you click in Import
![imagem](https://user-images.githubusercontent.com/14828021/35508785-8bb18e70-04e9-11e8-91e8-02e6c9fe040f.png)
# In plugin settings page
![imagem](https://user-images.githubusercontent.com/14828021/35508837-bb94d412-04e9-11e8-83ed-daa2ee1776c7.png)

**Comment by marcusgreen** [comment]
Many thanks for pointing that out (and doing translation). I think I need to change this  line in settings.php

$settingspage = new admin_settingpage('gfsettings' , 'Settings');

I am awaiting more feedback on yesterdays release (1.97) and I will fix this up when I have that.

**Comment by dinism** [comment]
1.97 is OK. Using it

**Comment by dinism** [comment]
THANKS
Portuguese (PT) Translation DONE.
