### ISSUE TITLE
regex processing should not be on by default

### ISSUE THREAD

**Issue by thepurpleblob** [marcusgreen/moodle-qtype_gapfill#31]
Most 'normal' users won't have a clue what regular expressions are. Therefore they can easily have regex characters in their answer that will 'break' the question. They will have absolutely no idea why. 

Regex processing is an advanced feature and should not be enabled by default.

**Comment by marcusgreen** [comment]
I agree that regex is an advanced feature that should not be enabled by default. However I made that decision very early on in the development process around 2011 and other more commonly used features depend on it, e.g. the use of or (with the broken bar |). 

 I have tried hard not to have any more than the most basic syntax required, so at minimum it is the delimiters  (e.g. [cat]), and then  once people are more used to it they might use cat|dog and perhaps !! for allowing a box to be empty.
It is possible to set regex processing to off in the config settings, another thing I could do is to offer a warning when a user goes to save a question with regex in the gap. What do you think?

**Comment by thepurpleblob** [comment]
Well... I got caught with this, https://moodle.org/mod/forum/discuss.php?d=365329.  Took half a morning of digging in the code to figure out :(

Yes - a warning would do the trick "You have RegEx characters in the gap. You might want to disable it". Or something vaguely like that!

**Comment by marcusgreen** [comment]
I will address this in the next release. It is an issue that had crossed my mind when I was doing the original development. I don't have a timescale yet.

**Comment by marcusgreen** [comment]
Looks like I didn't address this in the next release. But see my response to 
https://github.com/marcusgreen/moodle-qtype_gapfill/issues/32

**Comment by marcusgreen** [comment]
Fixed in the latest release in the Moodle.org plugins database (1.978) Thanks Howard.
