### ISSUE TITLE
regex is incompatible with 'dropdown' mode

### ISSUE THREAD

**Issue by thepurpleblob** [marcusgreen/moodle-qtype_gapfill#32]
In dropdown mode you can only select from a set of fixed answers (the right one plus the distractors). It makes no sense to allow regex processing of the answer. If the quiz setter puts regex control characters in the right answer it will be impossible to answer correctly (even if the correct choice is made).

**Comment by marcusgreen** [comment]
HI Purpleblobb
My apologies that it has been so long in responding. You are right that this should be addressed. There is also a slightly related issue that people may use regex characters without knowing they have a special meaning, and also people can accidentally paste html into the gaps which stops the question working properly. These last two items might be addressed by having the question type do two checks and then issue a warning dialog saying 'You appear to be using regex characters, do you mean to, Continue save yes or no', and 'You appear to have html characters in your gaps, you almost certainly don't want that, Continue yes or no'. Or something similar.

I am in the late stages of a new release and such a change will not be in that release but I will factor it in for the next release.

**Comment by marcusgreen** [comment]
Regex checkbox is disabled when dropdown is selected in editing form. Issue closed in release 2.11 (Just under 2 years from report to fix :( )
