### ISSUE TITLE
Still problems with spaces and selects

### ISSUE THREAD

**Issue by thepurpleblob** [marcusgreen/moodle-qtype_gapfill#33]
This is not (yet anyway) a fully formed report but you might have some ideas. As happened before with wrong answers and drop-down selects (https://github.com/marcusgreen/moodle-qtype_gapfill/issues/24), the 'selected' link is missing for right answers (sometimes!) such that the answer display shows no answer in the dropdown. 

Dumping the variables just before the answer select is displayed shows this. 

array(7) {
  [" COCA"]=>
  string(5) " COCA"
  [" Hansard"]=>
  string(8) " Hansard"
  [" Time"]=>
  string(5) " Time"
  [" GloWbE"]=>
  string(7) " GloWbE"
  ["NOW"]=>
  string(3) "NOW"
  [" SCOTS"]=>
  string(6) " SCOTS"
  [" EEBO"]=>
  string(6) " EEBO"
}
string(6) "GloWbE"

Where the first array is $selectoptions (the possible answers) and the second string the $currentanswer. As can be seen there are extra spaces stopping a match being made in html_writer::select (in renderer.php). 

The odd thing is the question definition...

![screen shot 2018-02-07 at 14 12 37](https://user-images.githubusercontent.com/664139/35920868-055978e0-0c11-11e8-8edf-ca69e28c1eea.png)

So, while there are some spaces in the distractors there isn't in the question. So, how did the space end up in the select list for GloWbE. 

Result is therefore displayed thus...

![screen shot 2018-02-07 at 14 14 54](https://user-images.githubusercontent.com/664139/35920999-5e14b77e-0c11-11e8-9d93-51aa40e856ba.png)

I haven't been able to replicate this with a new question but we have a number of existing questions that display this issue. It's not a one-off.

**Comment by thepurpleblob** [comment]
The space is there in the serialised data returned at $qa->get_step(0)->get_qt_var('_allanswers')

But, I'm starting to loose any kid of grip of how this works.

`string(123) "a:7:{i:0;s:5:" COCA";i:1;s:8:" Hansard";i:2;s:5:" Time";i:3;s:7:" GloWbE";i:4;s:3:"NOW";i:5;s:6:" SCOTS";i:6;s:6:" EEBO";}"`

**Comment by marcusgreen** [comment]
Can you create an example at 
http://vledevelop.co.uk/moodle/

With a teacher name of t1 and password of test
MG

**Comment by marcusgreen** [comment]
Actually I am creating it now you will see an example quiz there shortly.

**Comment by thepurpleblob** [comment]
You can have the question exported as XML if you like but I was unable to create a new question and reproduce it. I appreciate that this isn't very helpful...

**Comment by marcusgreen** [comment]
You can send it to me at marcusavgreen at gmail dot com. This is not an issue I have seen previously.

**Comment by thepurpleblob** [comment]
Better still, I'll get a backup of the thing.

**Comment by marcusgreen** [comment]
Even more bettererer

**Comment by marcusgreen** [comment]
I just restored the course and it looks like there is a space after each comma in the distractor, i.e. COHA, COCA, SCOTS, GloWbE, NOW, Soap Operas
If I remove the gaps and save there are no more spaceds.

**Comment by thepurpleblob** [comment]
But GlowbE (the correct answer) wasn't in the distractors??

**Comment by marcusgreen** [comment]
You are correct. I just did a fresh restore, GloWbE is not in the distractors it is the correct answer in the brackets, and there are no spaces between the distractors, here is a copy from that fresh install of the distractors. EEBO,COCA, SCOTS, NOW,Time,Hansard

**Comment by thepurpleblob** [comment]
Sooo.....?

**Comment by marcusgreen** [comment]
The question appears to work how I would expect, I see the items in the drop down without any unexpected space, when I select the correct answer It marks it correct, when I select anything else it marks it incorrect.... skype, hangout?

**Comment by thepurpleblob** [comment]
Ok... no worries, I'm reluctant (for either of us) to spend loads of time on it. Usually it turns out that someone has done something creative to break it. I suspect the answer is to avoid spaces.
