### ISSUE TITLE
Can not find data record in database table question_gapfill.

### ISSUE THREAD

**Issue by eganet2002** [marcusgreen/moodle-qtype_gapfill#34]
I just upgraded the plugin and suddenly I start getting this error for my quizzes.

I have ran cron several times as recommended by this post: https://docs.moodle.org/33/en/error/moodle/invalidrecord

Any solution? I have lot's of quizzes I can't access.

**Comment by marcusgreen** [comment]
What versions were you upgraded from and to?

**Comment by marcusgreen** [comment]
No log handling enabled - using stderr logging
Created directory: /var/db/net-snmp
Created directory: /var/db/net-snmp/mib_indexes
!!! <p>Error: Database connection failed</p>

**Comment by marcusgreen** [comment]
What database type are you using (i.e. are you using MySQL or MS-SQL Server or PostGres)

**Comment by eganet2002** [comment]
I upgraded to Version 
1.971 
2018020300. 
I cant remember the previous version.

**Comment by eganet2002** [comment]
How do I check the database I am using? I am a bit new here on moodle.
Thanks

**Comment by marcusgreen** [comment]
Can you go to admin and set debug to developer and see if you get more information when you attempt to use the questions

**Comment by marcusgreen** [comment]
Email me directly at marcusavgreen @ Gmail dot com

**Comment by eganet2002** [comment]
OK, Sorry didn't see you last message. Gonna Email you now.

**Comment by andreaspapazois** [comment]
Hello,
I have a similar issue with the above mentioned after migrating to a newer moodle/gapfill plugin version. I attach what I get from developer's debug mode plugin.
![Screenshot from 2022-02-23 21-24-27](https://user-images.githubusercontent.com/8005542/155393930-b5f25c68-efda-44b8-bf5e-e4bf7d3817d1.png)
Do you have any idea how this can be resolved? Running the cron job was not of any help.
