### ISSUE TITLE
Quiz answers with ? marked as wrong answer

### ISSUE THREAD

**Issue by neeesn** [marcusgreen/moodle-qtype_gapfill#40]
1) Create a quiz with "shuffle within questions" set to yes

2) insert an gapfill question

3) In one of the question texts make an test with an ?

4) Run the quiz.

The quiz look like this with out ? :
![firefox_E6KGrsEP5o](https://user-images.githubusercontent.com/1931926/55067280-b89ee300-507f-11e9-8f96-b0880292f1d5.png)

But with ? in the question text the answer is marked a wrong:
![firefox_DiDOci7DV8](https://user-images.githubusercontent.com/1931926/55067236-a7ee6d00-507f-11e9-818e-0df994267579.png)

So the quiz result is wrong because of ? in the quiz question.

Moodle 3.4.3+

**Comment by marcusgreen** [comment]
Can you check if the regular expression checkbox is set. I ask because ? is a special character and regex is set on by default (possibly not a good decision)

**Comment by marcusgreen** [comment]
I am assuming that the issue went away when you unchecked the regex option. If not, please re-open with more information.

**Comment by neeesn** [comment]
Sorry for very late answer. We updated the Moodle version and it was all good.
