### ISSUE TITLE
Selected options not displaying in dropdown mode, but are displaying in drag and drop mode

### ISSUE THREAD

**Issue by davefoord** [marcusgreen/moodle-qtype_gapfill#41]
I use this plugin loads on many different moodles (and love it by the way), but I have uncovered an unusual issue that I cannot work out.

I have created the following question:

---
<h3>Identify the ADRV</h3>
<p><strong>Below are three scenarios. For each one, identify which type of ADRV is being committed, by dragging the options from below into the correct positions.</strong></p>
<p><em>1) A coach is buying and selling anabolic agents to athletes. He suggests to his athletes that they should start using these anabolic agents to dramatically improve their performance and appearance. UK Anti-Doping work with law enforcement to enter his home where they find large quantities of drugs in labelled bags.</em></p>
<p>The ADRV for this would be [Trafficking|Possession] and/or [Trafficking|Possession].</p>
<p><em>2) UK Anti-Doping received information that an athlete was regularly using Cannabis and MDMA (Ecstasy) while out partying. A few days later the athlete was tested during an in-competition period and traces of the substances were found in their system.</em></p>
<p>The ADRV would be [Presence].</p>
<p><em>3) An athlete was representing his nation for the first time at a junior international event. He was selected for a test however he refused to provide a sample saying that he didn't have to because he was under 18. Despite conversations with the lead DCO he still refused to provide a sample.</em></p>
<p>The ADRV would be [Evading, Refusing or Failing].</p>

----
There are then a series of 'distractors' added as well. When I use this activity in drop down mode, when the user has made choices and checks the answer - it tells them which are right and wrong, but some of the options it shows what they entered and others don't. I have attached a screen shot showing what I mean. There doesn't seem to be any pattern (that I can see) as to which boxes or which options do or don't display on the feedback screen.

If I change the options so as to use drag and drop, it works as it should.

I have tested this with styles disabled in the browser, so I don't think this is a theme issue.

Any ideas?

![Capture](https://user-images.githubusercontent.com/28855774/58800518-00059a80-8600-11e9-9acd-5a4679495137.PNG)

**Comment by marcusgreen** [comment]
It looks to me like there is an issue when in dropdown mode. I will investigate further.

**Comment by marcusgreen** [comment]
Hi Dave, I have finally got around to looking at this and I was not able to reproduce what you are seeing.  Can you confirm the browser that you are using and if the 'missing fields' are present but hidden. Probably the easiest way is if you can give me teacher access to a course where I can see this happening.

**Comment by marcusgreen** [comment]
This issue turned out to be triggered by having a space before or after any wrong/distractor options. For now it can be eliminated by not having that space. The next version will do a trim on the distractors dispay.
