### ISSUE TITLE
Gapfill capitalises correct answers under certain conditions

### ISSUE THREAD

**Issue by mkpelletier** [marcusgreen/moodle-qtype_gapfill#42]
Moodle Version: 3.5.3+
Gapfill version: 2019021600

A dropdown gap fill question, using the default text options, will automatically capitalise the correct answers, while leaving the distractors uncapitalised. The savvy student will pick up on this and infer the correct answers.

Disabling regex seems to fix the problem, but it does leave that option unavailable for use.

**Comment by marcusgreen** [comment]
That is interesting, I was not aware of that. I will reproduce it and work on it. Thank you for reporting.

**Comment by marcusgreen** [comment]
My apologies for taking so long to get back to you on this. I have just tried to reproduce this without success. I have searched through the code for functions that might change the case of text without identifying any and so I am rather mystified as to why this might happen. I admit I am not running exactly the same Moodle and version of Gapfill as you describe, but I cannot recall ever writing code to change the case of text. Do you have any more information on this, has anything else shown up. I can give you access to a course running current versions of the code to see if you can reproduce it if that would be useful.

**Comment by marcusgreen** [comment]
I am closing this ticket as I was never able to reproduce it.
