### ISSUE TITLE
 Incorrect brackets interpretation

### ISSUE THREAD

**Issue by szyper-sakrona** [marcusgreen/moodle-qtype_gapfill#44]
I needed some special answers in my quiz (Excel quiz) so I choose a bracket answers [ ( ] and [ ) ] (without spaces, of course - to clear the view). And my surprise was that those symbols was **incorrectly** recognized as wrong answers. I know it is hard to include this special symbol - but maybe there is another way (like choose similar to normal brackets symbol) to solve this error?
What do you think?
Regards

**Comment by marcusgreen** [comment]
can you export your current attempts to xml and make available to me, or give me teacher access to a course where you are doing this. Email me at marcusgreen at mailbox.org. Have you tried alternative delimters e.g. {word}

**Comment by szyper-sakrona** [comment]
Maybe it is easier to make simple question with text and one [(] delimiter. Already tried different delimiters  { # @ with no effect - when testing the question with preview the attempt has 0 points from 1 available.  Also the dollar symbol $ has similar effect - maybe the C language is the source of this problem. But [!] and [&] are ok - working good.

**Comment by marcusgreen** [comment]
You can turn regular expressions off, would that help?

**Comment by szyper-sakrona** [comment]
Moodle regex options? Could you point me which option exactly?

**Comment by marcusgreen** [comment]
Scroll down from here
https://docs.moodle.org/37/en/Gapfill_question_type#Example_questions_available
It is not well documented, its under More options/disable regex

**Comment by marcusgreen** [comment]
Regex should probably have been disabled by default when I first created the question type, but that was back in 2011. Let me know if that works for you.

**Comment by szyper-sakrona** [comment]
Yes, with disable regex it works ok, thanks for clarification my question, resolved.

**Comment by marcusgreen** [comment]
Delighted to hear it. If you have a nice question that shows an interesting way of using the question type I'd love to see it.

**Comment by szyper-sakrona** [comment]
I like very much your aka "constructive" - or formative answering in gapfill/QtypeWordselect. In my opinion it should be more educational that simple abcd answers. Thanks for you hard work!
