### ISSUE TITLE
case sensitivity issue with GAPFILL questions

### ISSUE THREAD

**Issue by dipakburnwal** [marcusgreen/moodle-qtype_gapfill#45]
Hi,
Recently I am facing a issue with GAPFILL questions. when show more case sensitivity is not selected and yet if you do not capitalize it, it does not count the correct answer toward the total points but you do get a green check mark like it is correct. 
Really appreciate if you could look into this issue and provide us the fix on this

Thanks, Dipak

**Comment by marcusgreen** [comment]
I'll need examples of the questions and a detailed description of what the settings and actions were. I suggest you export to xml format and send to marcusgreen at mailbox.org
