### ISSUE TITLE
Answers that include the plus (+) sign are not shown as correct

### ISSUE THREAD

**Issue by hkalant** [marcusgreen/moodle-qtype_gapfill#46]
Steps to replicate:
1. Set up a gapfill question.
2. Give it a title.
3. Add the following question: At rest a neuron has a membrane potential of [-70mV] this is referred to as the [resting potential] and is maintained by a [sodium potassium pump]. When it is time for the neuron to send a signal [sodium_1] channels open and [sodium_2] flows into the neuron, this causes the inside of the cell to become [positive] with respect to the outside. This is called [depolarisation]. Once the potential reaches approximately [+40mV] sodium channels [close] and [potassium-1] channels open. This stage is called [repolarisation] and the inside of the neuron becomes [negative] with respect the outside. As [potassium_2] channels close slowly, the potential of the cell drops below -70mV, which is referred to as [hyperpolarisation], this is corrected by ions leaking out of the cell. Drag the correct answer in the appropriate boxes.
4. Check Case Sensitive.
5. Click Save Changes.
6. Preview the question and drag +40mV right after the word _approximately_
7. Submit all and finish.
8. Update the display options so you can see whether it is shown as correct or not.
9. +40mV is shown as red/incorrect.

Moodle 3.7.2
Gapfill 1.977

**Comment by marcusgreen** [comment]
Have you tried disabling regular expressions. Scroll down from here to see the setting.
https://docs.moodle.org/38/en/Gapfill_question_type#Example_questions_available

**Comment by hkalant** [comment]
Yeah, that works. Thanks!
