### ISSUE TITLE
letterhints column missing from database?

### ISSUE THREAD

**Issue by kwincks** [marcusgreen/moodle-qtype_gapfill#47]
Hi , i get this SQL error in the Apache Logs from PHP7, (Ubuntu18.04).

Default exception handler: Error reading from database Debug: Unknown column 'letterhints' in 'field list'\nSELECT answerdisplay, delimitchars, casesensitive, noduplicates, disableregex, fixedgapsize, optionsaftertext, letterhints FROM mdl_question_gapfill WHERE question = ?\n[array (\n  0 => '12623',\n)]\nError code: dmlreadexception\n* line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown\n* line 1245 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()\n* line 1571 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()\n* line 1543 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()\n* line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()\n* line 792 of /question/type/questiontypebase.php: call to moodle_database->get_record()\n* line 66 of /question/type/gapfill/questiontype.php: call to question_type->get_question_options()\n* line 939 of /lib/questionlib.php: call to qtype_gapfill->get_question_options()\n* line 1008 of /lib/questionlib.php: call to _tidy_question()\n* line 164 of /mod/quiz/attemptlib.php: call to get_question_options()\n* line 169 of /mod/quiz/locallib.php: call to quiz->load_questions()\n* line 2425 of /mod/quiz/locallib.php: call to quiz_start_new_attempt()\n* line 111 of /mod/quiz/startattempt.php: call to quiz_prepare_and_start_new_attempt()\n, referer: https://www.xxxxxx.nsw.edu.au/moodle/mod/quiz/view.php?id=12963

and Moodle 3.7.1 throws the error 
" Error reading from database

More information about this error"

the letterhints column doesnt actually exist. all the questions using gapfill cause this error.
I updated to the latest Gapfill and no change.
Please help. Thanks

**Comment by marcusgreen** [comment]
The letterhints collum was introduced in the move from version 1.961 and 1.97 in February 2018.
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
The code that adds the column can be seen here
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/bc2eeca21d1791edde3fee801d086c09ba9edc89/db/upgrade.php#L58

I am not certain why you don't have that column. The new column adds a single character column to a table that implements the feature here
https://docs.moodle.org/38/en/Gapfill_question_type#Letter_Hints
Assuming you are not using that feature nothing bad will be happening apart from that error message (which I assume doesn't show up unless debugging is set to developer).

Uninstalling and re-installing the question would fix the issue, but that is usually not possible if you already have numbers of the questions. If you are comfortable modifying the database structure adding a column to the question_gapfill will fix the issue. If that is not a possibility email me directly at marcusgreen @ mailbox.org.
(Actually email me there anyway..)

**Comment by kwincks** [comment]
Manually added letterhints column to database. quizes are working again. DMed Marcus.
