### ISSUE TITLE
HTML entities and answer size

### ISSUE THREAD

**Issue by getget1980** [marcusgreen/moodle-qtype_gapfill#49]
Hello, when I use html character ¯ (& macr;) in one of my answers, the answer box size is not correct. I think the answer size is the size of the HTML encoding (6 characters) and not the character itself (1 character).

It probably has to deal with this part of the code in question.php ... but I don't know how to solve the problem.

    public function get_size($answer) {
        $answer = htmlspecialchars_decode($answer);   // <--- I think the problem stands here ... shouldn't use   html_entity_decode instead ?
        $words = explode("|", $answer);
        $maxlen = max(array_map('strlen', $words));
        return $maxlen;
    }

**Comment by marcusgreen** [comment]
My apologies for the delay in responding to this. If this is still an issue could you give me more details. This is how it appears when I tried it, but I could be doing  something different to you.

<img width="639" alt="special_characters" src="https://user-images.githubusercontent.com/732202/128603519-0f264478-fc3d-454e-a61b-e1a626bfa79e.png">

**Comment by marcusgreen** [comment]
Closing, no response.
