### ISSUE TITLE
fail to recognize symbols 

### ISSUE THREAD

**Issue by olivia7506** [marcusgreen/moodle-qtype_gapfill#50]
Our Spanish teacher reported that the system will mark correct answers incorrect (see the screenshot below). It seems like the system cannot read the symbols (e.g. ?, !,¿) which are essential language components in Spanish. Could you help to fix this issue? Thank you!
![image](https://user-images.githubusercontent.com/56623733/82638954-58cbaa00-9c3a-11ea-835c-9807790ccae5.png)

**Comment by marcusgreen** [comment]
I Olivia, can you find the disable regular expressions option which you can see towards the bottom of this screen and let me know if it works when that is checked.

<img src =https://docs.moodle.org/38/en/images_en/1/1d/gapfill_edit11.png>

**Comment by olivia7506** [comment]
Dear Marcus Green,

Thanks for your quick reply.

I tried what you suggested. It worked. Thank you very much for your help!

Have a nice weekend!

Regards,
Olivia

**Comment by marcusgreen** [comment]
Delighted to hear it Olivia, you have confirmed that I need to set that box to be on as a default for new installations. Your question will have helped improve the plugin. Have a great weekend.
