### ISSUE TITLE
teacher switching roles to student causes display issues with gapfill question

### ISSUE THREAD

**Issue by CourtBard** [marcusgreen/moodle-qtype_gapfill#52]
I have created a question where the student needs to identify the parts of speech of each of the words in a sentence. The gap fill boxes and each of the words are placed into a table for alignment purposes, with one box in each cell of the top rom, and one word in each cell in the bottom row of the table.

When previewing the question, and when a student actually takes the quiz, everything lines up correctly and the question functions as expected. When a teacher uses the 'log in as' functionality of Moodle, the question layout goes crazy. The boxes and words align vertically, and the page footer jumps to the middle of the page.

I am using Moodle 3.9+ and version 1.979 of the gapfill plugin. I have pasted the html code that I am using for the table below.

The first picture is how the question looks when I preview the question or when a student logs in and takes the quiz. The second picture is how the question looks when the teacher 'logs in as' a student and views the question.

![preview_correct_01](https://user-images.githubusercontent.com/17094240/86517382-5cc41d80-bddd-11ea-99c0-d1b2f29cda7e.PNG)
![problem_02](https://user-images.githubusercontent.com/17094240/86517384-5f267780-bddd-11ea-8fe3-342a9874cb5d.PNG)

<table style="text-align:center;">
  <tbody>
    <tr>
      <td>[ART]</td>
      <td>[N]</td>
      <td>
        [PP]
      </td>
      <td>[ART]</td>
      <td>[N]
      </td>
      <td>
        [LV]
      </td>
      <td>
        <br>
      </td>
      <td>
        <br>
      </td>
      <td>
        <br>
      </td>
      <td>
        <br>
      </td>
      <td>
        [ADJ]
        <br>
      </td>
      <td>
        [ADJ]
        <br>
      </td>
      <td>
        [N]
        <br>
      </td>
      <td>
        <br>
      </td>
      <td>
        <br>
      </td>
      <td>
        [PP]
        <br>
      </td>
      <td>
        [ADJ]
        <br>
      </td>
      <td>
        [N]
        <br>
      </td>
      <td>
        [ART]
        <br>
      </td>
      <td>
        [N]
        <br>
      </td>
      <td>
        [PP]
        <br>
      </td>
      <td>
        [ART]
        <br>
      </td>
      <td>
        [N]
        <br>
      </td>
    </tr>
    <tr>
      <td>The
        <br>
      </td>
      <td>habits
        <br>
      </td>
      <td>of
        <br>
      </td>
      <td>the
        <br>
      </td>
      <td>child
        <br>
      </td>
      <td>are,
        <br>
      </td>
      <td>as &nbsp;
        <br>
      </td>
      <td>it &nbsp;
        <br>
      </td>
      <td>were, &nbsp;&nbsp;
        <br>
      </td>
      <td>so &nbsp;&nbsp;
        <br>
      </td>
      <td>many
        <br>
      </td>
      <td>little
        <br>
      </td>
      <td>hammers
        <br>
      </td>
      <td>beating &nbsp;&nbsp;
        <br>
      </td>
      <td>out
        <br>
      </td>
      <td>by
        <br>
      </td>
      <td>slow
        <br>
      </td>
      <td>degrees
        <br>
      </td>
      <td>the
        <br>
      </td>
      <td>character
        <br>
      </td>
      <td>of
        <br>
      </td>
      <td>the
        <br>
      </td>
      <td>man.</td>
    </tr>
  </tbody>
</table>
<br>
<br>
<p></p>

**Comment by marcusgreen** [comment]
Could you export your questions as XML and email as an attachement to marcusgreen at mailbox.org. Email me anyway and I will give you teacher access to a site of mine with the latest code so we can collaborate to track down the issue/cause.

**Comment by CourtBard** [comment]
I emailed you the question.
I also just noticed that the option to 'Show the number of correct responses once the question has finished' is always checked. Even when I uncheck the box and save the question, when it reloads, the box is checked again. There is no way to save the question with the box unchecked.

**Comment by marcusgreen** [comment]
My apologies for the delay in responding, I don't think I was able to reproduce this. I will close the ticket, but feel free to re-open/re-post if the issue is still in the code/causing problems.
