### ISSUE TITLE
Preview error

### ISSUE THREAD

**Issue by dinism** [marcusgreen/moodle-qtype_gapfill#54]
I updated for version 2.00 (Moodle directory) with Moodle 3.9
After you create a question and you preview it with any type of the display answers, when you submit i got this error:

Exception - Argument 1 passed to qtype_gapfill_renderer::get_feedback() must be of the type array or null, object given, called in [dirroot]/question/type/gapfill/renderer.php on line 285

**Comment by marcusgreen** [comment]
I have pushed an update that should fix this and will make it available in the plugins database shortly.

**Comment by marcusgreen** [comment]
I have just released version 2.03 to the plugins database. Please update your installation and confirm that issue has been fixed. My apologies for not spotting it.

**Comment by dinism** [comment]
DONE. 🥇 
Thanks a lot.
I'm a PT-PT translator. All done in AMOS.

**Comment by marcusgreen** [comment]
'I'm a PT-PT translator.' My hero!, thank you for your work on translation, it is wonderful to think it will make the plugin more widely useable.
