### ISSUE TITLE
Exception - syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by vk6hgr** [marcusgreen/moodle-qtype_gapfill#58]
Hello.

On our Moodle 3.5.7 instance, when we upgraded the plugin to version 2.07 and add or view a gapfill question and then  view the Quiz, Moodle throws a PHP error.

Plugin version 1.976 worked without error.

Debug log below:

`Got error 'PHP message: Default exception handler: Exception - syntax error, unexpected '?', expecting variable (T_VARIABLE) Debug: 
Error code: generalexceptionmessage
* line 409 of /question/type/gapfill/question.php: ParseError thrown
* line 827 of /question/type/questiontypebase.php: call to question_bank::load_question_definition_classes()
* line 814 of /question/type/questiontypebase.php: call to question_type->make_question_instance()
* line 289 of /question/engine/bank.php: call to question_type->make_question()
* line 189 of /mod/quiz/locallib.php: call to question_bank::make_question()
* line 2398 of /mod/quiz/locallib.php: call to quiz_start_new_attempt()
* line 111 of /mod/quiz/startattempt.php: call to quiz_prepare_and_start_new_attempt()',`

**Comment by marcusgreen** [comment]
What version of PHP are you using?

**Comment by vk6hgr** [comment]
> What version of PHP are you using?

7.0.33

**Comment by marcusgreen** [comment]
Unfortunatly the new code uses a feature that was introduced in PHP 7. nullable types
https://www.php.net/manual/en/migration71.new-features.php
A very quick search suggests that there is only one occurance of this.structure in the code. I have just pushed a new version that removes this feature
If you are confident in replacing files you can find the updated version here
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/question.php
I have not tested this in any way, and will do do by hand as soon as I can then push the updated code to the plugins database.
At the moment there are some automated tests that cover most of the code that should check if this has worked and you can follow its progress here
https://travis-ci.org/github/marcusgreen/moodle-qtype_gapfill/jobs/725142323

**Comment by vk6hgr** [comment]
Many thanks. I realise our version is old, and we're actually updating plugins in order to prepare for the major PHP and Moodle upgrade. I'll try the changed code.

**Comment by marcusgreen** [comment]
I should have included the tests with PHP 7.0 in the automated tests (as I have done now). However I recommend you upgrade to PHP 7.2 as soon as you can because other developers will start using features like this in upcoming versions of Moodle plus  the later versions of PHP offer some performance benefits.

**Comment by marcusgreen** [comment]
My apologies releasing with this issue in place. Its 7.20 AM for me, I will monitor any feedback you post here. Good luck.

**Comment by marcusgreen** [comment]
Unfortunately the travis automatic testing  does not appear to support 7.0 so automatic testing is not possible.

**Comment by marcusgreen** [comment]
I will close on the assumption that there was a bug when using PHP7.0 and the code change in an update has fixed that.
