### ISSUE TITLE
ERROR in Moodle 3.5+

### ISSUE THREAD

**Issue by germanvaleroelizondo** [marcusgreen/moodle-qtype_gapfill#59]
Moodle 3.5+
When debuggin set to developer:

Error: mdb->get_record() found more than one record!

    line 1583 of /lib/dml/moodle_database.php: call to debugging()
    line 1543 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
    line 1263 of /lib/questionlib.php: call to moodle_database->get_record()
    line 1317 of /lib/questionlib.php: call to question_get_top_category()
    line 487 of /question/editlib.php: call to question_make_default_categories()
    line 328 of /question/editlib.php: call to question_build_edit_resources()
    line 134 of /mod/studentquiz/viewlib.php: call to question_edit_setup()
    line 118 of /mod/studentquiz/viewlib.php: call to mod_studentquiz_view->load_questionbank()
    line 82 of /mod/studentquiz/view.php: call to mod_studentquiz_view->__construct()

This page did not call $PAGE->set_url(...). Using https://apuntesenlinea.fmvz.unam.mx/mod/studentquiz/view.php?id=9480&category=2921%2C34145&lastchanged=13228

    line 600 of /lib/pagelib.php: call to debugging()
    line 820 of /lib/pagelib.php: call to moodle_page->magic_get_url()
    line 42 of /admin/tool/mobile/lib.php: call to moodle_page->__get()
    line 600 of /lib/outputrenderers.php: call to tool_mobile_before_standard_html_head()
    line 95 of /theme/boost/classes/output/core_renderer.php: call to core_renderer->standard_head_html()
    line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_boost\output\core_renderer->standard_head_html()
    line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
    line 34 of /var/www/moodledata/localcache/mustache/1599738423/boost/__Mustache_f2e7c36b860a1883a3ce7bc294429a31.php: call to Mustache_Context->findDot()
    line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_f2e7c36b860a1883a3ce7bc294429a31->renderInternal()
    line 177 of /lib/outputrenderers.php: call to Mustache_Template->render()
    line 32 of /theme/boost/layout/embedded.php: call to renderer_base->render_from_template()
    line 1273 of /lib/outputrenderers.php: call to include()
    line 1203 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 1122 of /lib/outputrenderers.php: call to core_renderer->header()
    line 2869 of /lib/weblib.php: call to core_renderer->redirect_message()
    line 149 of /mod/studentquiz/viewlib.php: call to redirect()
    line 118 of /mod/studentquiz/viewlib.php: call to mod_studentquiz_view->load_questionbank()
    line 82 of /mod/studentquiz/view.php: call to mod_studentquiz_view->__construct()

Yet, the module seems to work, but produces many ERROR redirects.

**Comment by marcusgreen** [comment]
Thanks German, can you confirm this is all with StudentQuiz and what version of PHP it is. I am asking about PHP because there is an (almost certainly unrelated) issue with PHP 7.0

**Comment by marcusgreen** [comment]
Which version of StudentQuiz are you using, I have just installed the latest version against Moodle 3.9 and Gapfill worked on a very quick test.

**Comment by marcusgreen** [comment]
Am closing this on the assumption you would have followed up if it were a persisting problem. If I am wrong feel free to re-open/re-create..
