### ISSUE TITLE
Problems with MSSQL

### ISSUE THREAD

**Issue by SteffenPegenau** [marcusgreen/moodle-qtype_gapfill#6]
While updating gapfill I got a SQL error I was able to fix by changing the sql statement in db/upgrade.php line 77 to:

$sql = "ALTER TABLE " . $CFG->prefix . "question_gapfill add disableregex tinyint default 0";
            $DB->change_database_structure($sql);

Quick and dirty but I can't see a real functional difference.

**Comment by marcusgreen** [comment]
I have updated live to reflect this
