### ISSUE TITLE
singleuse field missing

### ISSUE THREAD

**Issue by aspark21** [marcusgreen/moodle-qtype_gapfill#60]
Moodle 3.7.8 & Gapfill master
Updating from gapfill 2020082901 to 2020090800

Field "singleuse" does not exist in table "question_gapfill"

More information about this error

×Debug info:
Error code: ddlfieldnotexist
×Stack trace:
line 651 of /lib/ddl/database_manager.php: ddl_field_missing_exception thrown
line 98 of /question/type/gapfill/db/upgrade.php: call to database_manager->change_field_default()
line 644 of /lib/upgradelib.php: call to xmldb_qtype_gapfill_upgrade()
line 1869 of /lib/upgradelib.php: call to upgrade_plugins()
line 711 of /admin/index.php: call to upgrade_noncore()

**Comment by marcusgreen** [comment]
Hi Alistair my apologies for the bug. 

There is a line in the upgrade file that reads
    if ($oldversion < 2020070400) {
        if (!$dbman->field_exists('question_gapfill', 'singleuse')) {

An the oldversion needs to be set to a later date to install the new field in the table.  I will update the github file ASAP then get it into the plugins database.

**Comment by aspark21** [comment]
No worries. Thanks Marcus!

**Comment by marcusgreen** [comment]
I have just bumped the version number and modified the upgrade clause in github  master.This should fix the issue, but I have not tested it at all.

**Comment by aspark21** [comment]
Seems to have done the trick.

I did get this but I think it was due to the earlier incomplete attempt:

Cannot downgrade qtype_gapfill from 2020091100 to 2020082902.

More information about this error

×Debug info:
Error code: cannotdowngrade
×Stack trace:
line 404 of /lib/upgradelib.php: downgrade_exception thrown
line 101 of /question/type/gapfill/db/upgrade.php: call to upgrade_plugin_savepoint()
line 644 of /lib/upgradelib.php: call to xmldb_qtype_gapfill_upgrade()
line 1869 of /lib/upgradelib.php: call to upgrade_plugins()
line 711 of /admin/index.php: call to upgrade_noncore()

**Comment by aspark21** [comment]
Actually yes there is still a thin about that - it's the next step in the upgrade.php which relies on the singleuse column needs to have a higher savepoint - https://github.com/marcusgreen/moodle-qtype_gapfill/blob/f4b30561312304e909ab758f24077fe2cd7da688/db/upgrade.php#L91

**Comment by marcusgreen** [comment]
I think as you go towards the end of the upgrade.php file the version needs to increase. The current last one is to fix an earlier error where the column type was wrong.  I am considering deleting the block containing         // Changing the default of field singleuse on table question_gapfill to 0. As it is purely about a default anyway. Removing it would probably only affect a small amount of people who would have useonce default to on, and I think once that was configured in the settings to their preference there would be no issue.

**Comment by marcusgreen** [comment]
Have pushed code to remove that block as it would only have applied to a small number of people.
