### ISSUE TITLE
Can I help I can do this on mobile browsers

### ISSUE THREAD

**Issue by cuchanu91** [marcusgreen/moodle-qtype_gapfill#63]
Hello
Can I help I can do this on mobile browsers
"" Instead of dragging answers into gaps, the answer will be clicked to select and then a gap will be clicked to drop into "
Thank you

**Comment by marcusgreen** [comment]
No, its a nice idea and it is how it works on the app but it is not in my current plans. I actually prefer this to drag and drop but it would take a whole bunch of time to implement.

**Comment by marcusgreen** [comment]
Closing as although I like the idea I will not be implementing in the foreseeable future.
