### ISSUE TITLE
Cannot drop answer onto input field

### ISSUE THREAD

**Issue by t-schroeder** [marcusgreen/moodle-qtype_gapfill#64]
If I want to drag the answer "Anwendung von physikalischen Effekten" into the second input field I have to drop it onto the area outlined in green here:

![image](https://user-images.githubusercontent.com/24255259/100386983-2a82b900-3027-11eb-8e59-044119ff3f4b.png)

In this screenshot I paused the JavaScript at the moment that I clicked the answer text to start dragging it. I set a breakpoint in jquery-ui.js in the function "_cacheHelperProportions". I did click the answer that I underlined in red. But then a copy of it is being created or made visible which I encircled on the right. That element then immediately gets moved to my cursor and I can drag it around. But when I drag it around it has different dimensions than in the screenshot. It's one line instead of four. I think that's why all the drop areas are effectively to the top and right of the input fields when dragging this specific answer. With the one-word answers I don't have this problem and with the two-word answers it's less pronounced.

**Comment by marcusgreen** [comment]
Can you export an example question to xml and send it to me at marcusgreen at mailbox.org

**Comment by marcusgreen** [comment]
Thank you for sending me the xml. I have reproduced the issue and will work on it further.

**Comment by t-schroeder** [comment]
Thanks for taking a look at this.

**Comment by marcusgreen** [comment]
I may have a solution, are you able to install an updated css file and purge caches, or are you limited to getting the next version from the moodle.org plugins database.

**Comment by marcusgreen** [comment]
I can make the modified version available for you to test on a publicly visible website.

**Comment by t-schroeder** [comment]
I can do anything on my dev machine. You can just send me the updated css for testing.

**Comment by marcusgreen** [comment]
Get a copy of the current version of this 
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/styles.css
purge caches and see if it helps

**Comment by t-schroeder** [comment]
That solves it. Thanks for the quick fix :)

**Comment by marcusgreen** [comment]
Thanks for the feedback, very much appreciated. Can I mention you in the credits for the next release 
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md

**Comment by t-schroeder** [comment]
Sure, much appreciated as well.
