### ISSUE TITLE
Answer correct but shown as incorrect

### ISSUE THREAD

**Issue by bho199** [marcusgreen/moodle-qtype_gapfill#66]
Hello! 
I added a quiz with Gap Fill but it tells every correct answer as incorrect. Any suggestions? 

<img width="1030" alt="Schermata 2020-12-15 alle 18 26 19" src="https://user-images.githubusercontent.com/31746660/102249814-0f5ae900-3f03-11eb-9b40-ef069c7c18fd.png">

<img width="1168" alt="Schermata 2020-12-15 alle 18 21 02" src="https://user-images.githubusercontent.com/31746660/102249266-775cff80-3f02-11eb-9570-90ec3d16b976.png">

**Comment by marcusgreen** [comment]
Please export to xml and send to me at marcusgreen at mailbox.org. Also check if there is anything hidden in the html

**Comment by bho199** [comment]
Thank you for your quick reply I did sent you the xml file as you asked me :)

**Comment by marcusgreen** [comment]
I am closing this as I have a memory it was to do with html within the opening and closing braces. If I am incorrect, please re-open/create a new ticket. (I should have updated at the time).
