### ISSUE TITLE
Gapfill marked out of

### ISSUE THREAD

**Issue by kamiobi** [marcusgreen/moodle-qtype_gapfill#68]
Marcus,
Sorry, I posted this to the moodle forums as well, but it looks like the XML files didn't get attached. 

A colleague, who uses the gapfill question type extensively, has an issue when using random questions. In one quiz, he has a maximum grade of 100 and total marks of 100.00. He has one question worth 40 points that pulls random questions from a category with three questions. Each question has four sentences. Three of the sentences in the question have one gap to fill, and the fourth sentence has two for a total of five gaps per question. When looking at them in preview mode, two are marked out of 10, and one is marked out of 7. Why aren't all three marked out of 10?

I have uploaded two xml files: one for the question that is marked out of 7 and another that is marked out of 10.  I have also added screenshots of what I'm seeing.

[xml.zip](https://github.com/marcusgreen/moodle-qtype_gapfill/files/5847423/xml.zip)

**Comment by marcusgreen** [comment]
Thanks for that, I will put it on my todo list for the upcoming weekend.

**Comment by marcusgreen** [comment]
Would you be able to either give me either a moodle export of a course that illustrates this, or teacher access to a course I can login to?

**Comment by kamiobi** [comment]
Marcus,
I tried to upload the backup of the course here, but the file is too large. I put it in Google Drive. Here is the link:
https://drive.google.com/drive/folders/1NU0aLBlcLKc6jz8aBsrVBVhpvb2ECirk?usp=sharing

**Comment by marcusgreen** [comment]
I'm closing this because it looks like identifying the issue and then solving it would a reasonably significant amount of time and it is not an issue that has been raised by anyone else. My apologies, but have to focus on higher impact issues.
