### ISSUE TITLE
version required bump?

### ISSUE THREAD

**Issue by aspark21** [marcusgreen/moodle-qtype_gapfill#74]
Moodle: 3.5.18
Gapfill: latest master
Does not occur in 3.9 builds so it's probably relying on core functions from higher Moodle versions. 3.5 is out of support, so probably best to bump version required.

questiontype_test::test_save_question

    Error: Call to undefined method questiontype_test::assertIsArray()

  

    /var/www/html/question/type/gapfill/tests/questiontype_test.php:115

    /var/www/html/lib/phpunit/classes/advanced_testcase.php:80

  

    To re-run:

     vendor/bin/phpunit "questiontype_test" question/type/gapfill/tests/questiontype_test.php

**Comment by marcusgreen** [comment]
Thanks Alistair, I will take a look and probably release an update. The age of supported versions was starting to look a little implausible.

**Comment by marcusgreen** [comment]
I took another look at this assertIsArray seems to be part of the phpunit testing code. I'm not going to bump the required version on this next minor release, but I will update it in the master branch so it is updated to at least 3.5 in the release after this.

**Comment by marcusgreen** [comment]
Bumped in subsequent release. Closing now, thank you Alistair
