### ISSUE TITLE
Plugin should ignore gaps in HTML comments

### ISSUE THREAD

**Issue by t-schroeder** [marcusgreen/moodle-qtype_gapfill#75]
**Describe the bug**
One of our users probably copied some question text from Word. The result was something like this:

```
<!--[if !msEquation]-->|ϑ| = [0,5] \( \cdot\: \pi \)
<!--[endif]-->
```

Moodle then treated the `if !msEquation` and `endif` as gaps and expects the students to provide answers for those. Since the students can't see these gaps they cannot get full points for the question even if they fill out all (visible) fields correctly.

**To Reproduce**
1. Create a question.
    1.1 As question text use the HTML code posted above.
    1.2 Set More Options -> Display Answers to "gapfill".
2. Preview the question.
3. Answer "0,5".
4. Get only 1 of 3 points.

**Expected behavior**
Gaps in HTML comments should be ignored by gapfill.

**Comment by marcusgreen** [comment]
Can you post an example here of the text you were using.

**Comment by t-schroeder** [comment]
The HTML snippet above is a minimal example. The actual question had some additional text and some more gaps. But why does that matter? The bug can be reproduced with the example I gave.

**Comment by t-schroeder** [comment]
I can't give you the exact question text that caused the problem for us because the teacher had already fixed that by the time she reported the problem to us. We had to look into the grade tables to see that there were originally four extra gaps in the question:

- if !msEquation
- endif
- if !msEquation
- endif

Users were getting at most 6/10 points for the question. We therefore concluded that the original question must have had `<!--[if !msEquation]--><!--[endif]-->` somewhere in there twice from copy-pasting a formula from some Microsoft program like Word.

I could take the current version and try to recreate how the original question might have looked like. Or you could just take a much simpler example like this:

```
<p>1 + 1 = [2]</p>
<!--[not a gap]-->
```
