### ISSUE TITLE
Regrading Gapfill Questions Deletes Student Response

### ISSUE THREAD

**Issue by teejaydecano** [marcusgreen/moodle-qtype_gapfill#79]
We are using Moodle 3.10 and have encountered several times this issue alongside other ones that have an effect on the regrading issue.

There are users who create several questions in one gapfill question entry. After saving the gapfill question, the system records the number of marks, let's say it's 15 points. Then, some users decide to edit the question and remove some items which would result in a lower number of total marks, let' say 10. This will then result in a problem in the marks that students get when they answer this gapfill question. Even if they get all the 10 items correct, the system will record this as 10 out of 15.

First concern: Is this something that users should not be doing when a gapfill question has already been saved? We have done a workaround where users copy and paste the HTML code, delete the content of the question text, then paste the copied HTML code which then allows the gapfill question to record the correct number of total marks.

Before this workaround, some users do manual regrading. Now, after regrading, the answers of the students in the individual manual grading view disappear after regrading the gapfill question.

Are these bugs in the question type or are there practices that we should not be doing at all for this question type?

Thank you so much for your time.
![2021-09-13 15 59 36](https://user-images.githubusercontent.com/90013757/133048149-9402f437-0dd0-4d83-a6dc-51f45442ccf3.jpg)

**Comment by teejaydecano** [comment]
[questions_1st_Unit_Test_G1_Queen_of_Patriarchs_Default_for_Mathematics.xml.zip](https://github.com/marcusgreen/moodle-qtype_gapfill/files/7152605/questions_1st_Unit_Test_G1_Queen_of_Patriarchs_Default_for_Mathematics.xml.zip)

**Comment by marcusgreen** [comment]
I have not come across this before, I will investigate. Thank you for including the example. There will be a delay before I can look at this in depth.

**Comment by teejaydecano** [comment]
Thank you.

**Comment by marcusgreen** [comment]
Before I start to investigate, can you confirm that this does not happen when using core question types?

**Comment by teejaydecano** [comment]
Yes. It does not happen with core question types. 

Thank you.

**Comment by marcusgreen** [comment]
Quiz questions have a default mark and that mark allocated  to an instance of the question when it is part of a quiz. You can see this with the core select missing words where it has a field for Default mark which defaults to one and is unrelated to the number of words.  That value can be edited by the user from within the question. The difference with my question types Gapfill and Wordselect is that it is set to a hard coded one mark per gap/word. However the grade a student actually gets is set in the exam. So if you have a gapfill question with three gaps by default the question will receive three marks in the quiz but you can change it to whatever value you like (see the screenshot below).

Editing a question cannot control that value awarded in the quiz as it may appear in several quizzes and each quiz can give a different mark for that question in that quiz. So if a user changes the number of Gaps the grade in the quiz will not change, but can be updated in the quiz. If the question is added to a different quiz the new gap count (2) will mean the default grade in the quiz will be 2 marks for that instance. I have just tested with the core "select missing words question" type. For that question type the user must enter the default "by hand". If you change the number of words the number of marks will stay the same (but you can change the number of marks in any instance of the quiz). 

The Gapfill question type is installed in around 3656 sites
https://moodle.org/plugins/qtype_gapfill/stats
And has been in use for over 10 years, and as grading and marking is fundamental to its operation I would have expected issues related to it to have been reported during that time.

I created a "sister" question type Wordselect https://moodle.org/plugins/qtype_wordselect which has been adopted by the UK Open University, the originators of several of the Moodle core question type. Wordselect uses the same approach to marking as Gapfill and I have had no feedback questioning how the marking works.

The relationship between default mark and quiz/instance mark is not obvious, does my explanation make sense? 

<img width="1109" alt="GapfillQuiz" src="https://user-images.githubusercontent.com/732202/133942794-d95f5de1-334f-40d3-9d9f-5e8370783eb8.png">

**Comment by teejaydecano** [comment]
Good day.

Thank you for your thorough response on the issue. I do understand what you
mean regarding the editing of points.

May I just explain some more the problems being encountered by some users?

There are users who create questions with 15 gaps. Then, they will edit
this and reduce this to 10 gaps. Even after changing the mark to 10, the
quiz still records scores over 15 points.

So a student who gets all correct answers for the 10 gaps but will only get
66% score.

Thank you.

Timothy Joseph P. Decano
EdTech Specialist
Certified Data Storyteller

**Comment by marcusgreen** [comment]
I will see if I can set up a publicly visible version of Moodle 3.10 with the question type so we can go over the various scenarios. I did try to import your questions but for some reason it wouldn't work locally, possibly becauwe of my local configuration. Can you email me directly at marcusgreen at mailbox.org
