### ISSUE TITLE
Missing Spaces in Correction (German)

### ISSUE THREAD

**Issue by PlotiniVox** [marcusgreen/moodle-qtype_gapfill#80]
I love to use qtype_gapfill in my moodle. My moodle is in German. The correction shows a text string that lacks spaces, see attachment.

**To Reproduce**
1. Go to moodle and enter a question with two or more solutions, e.g.: [solution1|solution2|solution3], [solution1|solution2|solution3], [solution1|solution2|solution3]
2. Start the quiz and enter wrong answers.
3. Look at the automatic correction
4. See all correct solutions listed, but lacking spaces between them. 

**Expected behavior**
Space between every possible solution. 

**Screenshots**
See screenshot

**Desktop:**
 - iOS, MacOS
 - chrome and safari
 - Moodle 3.10.3
 - qtype Version 2.132 (2021073100)

<img width="1300" alt="qtype issue" src="https://user-images.githubusercontent.com/95375058/144288530-b25c72f1-2104-48ee-bfe1-15e4f5633b0b.png">

**Comment by marcusgreen** [comment]
Can you confirm that you are missing a space between the feedback separator, so in english it should (perhaps does) say "red or green".

**Comment by PlotiniVox** [comment]
Yes, I confirm: It says „redorgreen“ instead of „red or green“.

**Comment by marcusgreen** [comment]
Can you paste the exact text of your question into here so I know I am doing exactly the same as you.

**Comment by marcusgreen** [comment]
Currently installing the German language pack

**Comment by PlotiniVox** [comment]
Here you are:

> civitas [civitatis] [f]
> 
> 
> 
> [Bürgerrecht|Gemeinde|Staat], [Bürgerrecht|Gemeinde|Staat], [Bürgerrecht|Gemeinde|Staat]
> 
> 
> 
> 
> 
> 
> 
>

**Comment by PlotiniVox** [comment]
screenshot of question.

<img width="1089" alt="qtype_screenshot" src="https://user-images.githubusercontent.com/95375058/144313298-448b7fe4-5ec2-40b1-9764-15302d6ca256.png">

**Comment by marcusgreen** [comment]
This is a bug in the string handling. I can give you a line where a small change will fix this when the language is set to German. It will look strange in English but that may not concern you. I will put a real fix in with the next release but that may be quite a wait (possibly after Christmas)  Are you confident in making changes to source code?

**Comment by marcusgreen** [comment]
https://github.com/marcusgreen/moodle-qtype_gapfill/commit/23b41ee6c66b3239c4d6b22610760dda16546bdc

**Comment by PlotiniVox** [comment]
Thank you very much for your quick fix.  Unfortunately  I am not able to edit source code.
I’m looking forward to your next release. No problem to wait for it.
Am 1. Dez. 2021, 22:55 +0100 schrieb Marcus Green ***@***.***>:

**Comment by marcusgreen** [comment]
Would you send an email to marcusgreen at mailbox.org I have a little question for you.

**Comment by marcusgreen** [comment]
I have just released the latest version of the Gapfill plugin which contains a fix for this. Thank you for reporting.

**Comment by PlotiniVox** [comment]
Hi Marcus

Thank you very much, it works now perfectly!
Much better for my students now!

Regards
Simon
Am 27. März 2022, 15:29 +0200 schrieb Marcus Green ***@***.***>:
