### ISSUE TITLE
Very large filling gaps

### ISSUE THREAD

**Issue by DrCadmus** [marcusgreen/moodle-qtype_gapfill#82]
Hello, excuse my English. I've been using gapfill, when I set up a question, the gaps to fill always take up a whole line. I'll pass you an image that shows the problem. I hope you can help me with this problem.

![image](https://user-images.githubusercontent.com/101917152/159108437-2084e44c-f984-4970-bb23-6ff08decccfe.png)

I wish the fill gap was smaller.

**Comment by marcusgreen** [comment]
What version of Moodle and what theme are you using?

**Comment by DrCadmus** [comment]
The versipn is 3.11 (Build: 20210517) (2021051700). I don't know the theme, I'm not an administrator

**Comment by marcusgreen** [comment]
Could you export an example gapfill question  as XML and attach it to a comment here. You only need teacher access to export questions. See here https://docs.moodle.org/311/en/Export_questions

**Comment by cShade0312** [comment]
Hi @marcusgreen , I am also having this issue where the "answer box" size is relative to the size of the browser window.

![image](https://user-images.githubusercontent.com/86537184/163170820-766f50ce-9286-41ab-8f3b-80a72c32384f.png)

**Comment by marcusgreen** [comment]
Closing this issue as it is old and I was not able to reproduce. Feel free to re-open/open a new ticket if this is still an issue.
