### ISSUE TITLE
Duplicate dragables in Moodle Mobile app

### ISSUE THREAD

**Issue by nstefanski** [marcusgreen/moodle-qtype_gapfill#85]
When viewing a drag & drop gapfill question in the Moodle Mobile app, there are two rows of duplicate dragables. Both groups work, so this bug does not affect functionality. The issue is only on the app, not in mobile browsers.

This is using the latest app version, 4.0.0 on iOS, and I've tested with sites using versions 3.10 and 4.0.1 of Moodle. I've attached a screenshot of the error, as well as the question text for the setup. I believe everything else should be using default settings, but I can share any additional info as needed.

![gapfill_bug](https://user-images.githubusercontent.com/18444936/169900846-1d45d55f-b19c-4b95-9297-ebd20b1d76f0.png)
![gapfill_setup](https://user-images.githubusercontent.com/18444936/169901178-76ce4ed3-d0ed-4240-985e-d6fc31b05894.png)

**Comment by marcusgreen** [comment]
Thank you for your feedback. Could you export York question as xml and save it here as an attachment. I have never seen that before.
https://docs.moodle.org/400/en/Export_questions

**Comment by nstefanski** [comment]
I'm having trouble uploading the xml file for some reason, but here it is as a gist: https://gist.github.com/nstefanski/9612706185af516b0fb32e3024d735c4

**Comment by marcusgreen** [comment]
The gist should be fine.

**Comment by marcusgreen** [comment]
This was fixed in release 2.3214. Thanks to Nicholas for the feedback
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
