### ISSUE TITLE
Distractors with HTML tags are displayed incorrectly

### ISSUE THREAD

**Issue by Amrita1991** [marcusgreen/moodle-qtype_gapfill#91]
**Description**
If the distractors have HTML elements e.g subscript / superscript they are not displayed correctly while the quiz is attempted

**To Reproduce**
1. Create a quiz
2. Add a new question of type Gapfill
3. add text with superscript/subscripts in distractors
4. Attempt the quiz

**Expected behavior**
The super/subscripts should show correctly

**Actual Behavior**
The super/subscripts are show as plain text

**Screenshots**
![gf1](https://user-images.githubusercontent.com/19415046/189349192-37b97e98-988f-409f-a2bd-4779d1bf1824.PNG)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser :Chrome(I have only tested it here)
 - Version 3.11.9

**Comment by marcusgreen** [comment]
How did you enter the text?

**Comment by Amrita1991** [comment]
I use the option of sub/superscript option from Atto editor.
![editorsnap](https://user-images.githubusercontent.com/19415046/189357140-0498085d-40e1-4fd2-a69b-9a180ecaa10f.png)

**Comment by marcusgreen** [comment]
Yes, that Is what I thought. Behind the scenes it is creating html like this
<sup>2</sup></p>
<sub>3</sub></p>
Which will not work with Gapfill
However with the core question type this will work.

<img width="663" alt="image" src="https://user-images.githubusercontent.com/732202/189358406-47ac9e24-39f9-40a5-89d1-b3e67ff2a258.png">

**Comment by Amrita1991** [comment]
I understand that when something is dropped into the gap, it changes into plaintext. I already have a suggestion on how we can  avoid false evaluation (i.e when answer has HTML elements it is evaluated as wrong even when the right option is dropped into the gap) that I will link with #43 soon. But when we can already display the correct  answer correctly during attempt then why not distractors?

**Comment by marcusgreen** [comment]
You being a developer rather changes things :). I don't know about the distractors, as HTML answers were not anticipated I have never worked on rendering the distractors as there would have been no benefit.

**Comment by marcusgreen** [comment]
This is a related issue
https://github.com/marcusgreen/moodle-qtype_gapfill/issues/43
The person who asked that is very experienced and knowledgable about this sort of thing.
I will be looking at the question type in about a week, but mainly to fix an issue with Moodle 4.0 linked to the drag/drop action and switching from jquery ui to native html5 drag drop, see this branch
https://github.com/marcusgreen/moodle-qtype_gapfill/tree/html5_dragdrop

**Comment by marcusgreen** [comment]
I am closing this because the gapfill question type was not designed to deal with html in either the distractors or the correct answers. This is because the drop targets are always a standard html textbox which will not render html. It would be nice if it did/could but it would require a significant amount of development that I am not in a position to do in the foreseeable future
