### ISSUE TITLE
an extra "if!supportLists" choice

### ISSUE THREAD

**Issue by synnac** [marcusgreen/moodle-qtype_gapfill#95]
In the choices list provided, sometimes there appears an extra "if !supportLists" and "Endif"choice. How can I fix the issue? Thank you!

![1665203602065](https://user-images.githubusercontent.com/88969475/194688403-b6fe1635-6b71-4dd1-ae6a-2a8269252a34.jpg)

**Comment by marcusgreen** [comment]
I don't know why you are seeing ifSupportsList. My guess is that you have some javascript injecting that, but that is just a guess. If you could export your question to xml and attach it to a message I will look at it. Alternatively if you give me access to the site where this is happening I will take a look at this. One other option is that I can give you access to a site where you can re-create the question to see what happens. I have done a search through the source code of the question type and it does not contain the string ifSupportLists.

**Comment by synnac** [comment]
> I don't know why you are seeing ifSupportsList. My guess is that you have some javascript injecting that, but that is just a guess. If you could export your question to xml and attach it to a message I will look at it. Alternatively if you give me access to the site where this is happening I will take a look at this. One other option is that I can give you access to a site where you can re-create the question to see what happens. I have done a search through the source code of the question type and it does not contain the string ifSupportLists.

I think I've figured our what happened. When I copy question text with  auto numbering into the editor, the text will contain some html codes with square brackets, which then will be treated by Gapfill plugin as choices. 
I think if there isn't a method to clear these codes, then we will have to avoid copying autonumbered texts from word.

The following is an example.  
`<p dir="ltr" style="text-align: left;"></p>
<p></p>
<p></p>
<p><span lang="EN-US"></span></p>
<p></p>
<p><span lang="EN-US" class="" style="font-size: medium;"></span></p>
<p><span lang="EN-US" class="" style="font-size: medium;">&nbsp;</span><span lang="EN-US" style="font-size: medium; text-transform: inherit;" class="">1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Mr. Turner</span><span style="font-size: medium; text-transform: inherit;" class="">’</span><span lang="EN-US" style="font-size: medium; text-transform: inherit;" class="">s
        lectures would not seem so [bland] to students if he didn't speak in such a
        dull tone of voice and if he included information that seemed [relevant] to
        their lives.</span></p>

<p>
    <span lang="EN-US" class="" style="font-size: medium;">2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </span>
    <span lang="EN-US" class="" style="font-size: medium;">Gang members are
        a menace to our neighborhoods. The only items on their [agenda] are theft and
        violence.Their [ruthless] methods</span><span class="" style="font-size: medium;">—</span><span lang="EN-US" class="" style="font-size: medium;">threats
        and smashed windows</span><span class="" style="font-size: medium;">—</span><span lang="EN-US" class="" style="font-size: medium;">cause terror among local business
        people.</span>
</p>

<p><br></p><br>
<p></p>`

**Comment by marcusgreen** [comment]
Ahh yes, I have thought about trying to detect unexpected html in gaps/distractors in the past, I will give it more thought. Thank you for getting back to me.

**Comment by synnac** [comment]
> Ahh yes, I have thought about trying to detect unexpected html in gaps/distractors in the past, I will give it more thought. Thank you for getting back to me. Perhaps I should strip all comments, as I cannot see any benefits from html comments when rendering a question type.

Thank you Marcus, you are the best!

**Comment by marcusgreen** [comment]
I am closing this issue now as it was addressed in release  2.136 as recorded in the changelog.
https://github.com/marcusgreen/moodle-qtype_gapfill/blob/master/changelog.md
Many thanks for your contribution, it will removed an issue that would almost certainly have been a problem for some users.
