### ISSUE TITLE
Not show drag icon in Moodle app!

### ISSUE THREAD

**Issue by bi1101** [marcusgreen/moodle-qtype_gapfill#96]
**Describe the bug**
In the Moodle app for drag and drop, the drag options are not surrounded by any border but clump together
Here is a picture:
![Screenshot_20221028-141300_IELTS Science](https://user-images.githubusercontent.com/15710921/198526656-4c87cdb9-fa1c-4470-9793-7483f8b20b47.jpg)

**Comment by marcusgreen** [comment]
Could you send me the text for the question so I can attempt to reproduce it.

**Comment by bi1101** [comment]
Yes here is the text:

The words in bold are quite advanced. Try replacing them with simpler words
1   It took at least 3,000 years for humans to learn how to domesticate the wild tomato and cultivate it for food. [grow]

2   This approach relies on the revolutionary CRISPR genome editing technique, in which changes are deliberately made to the DNA of a living cell, allowing genetic material to be added, removed or altered. [intentionally]/[changed]

3   This fast-track domestication could help make the world's food supply healthier and far more resistant to diseases, such as the rust fungus devastating wheat crops. [destroying]

4   We can now mimic the known domestication course of major crops like rice, maize, sorghum or others,' says Caixia Gao of the Chinese Academy of Sciences in Beijing. [copy]

5   Over many generations, peoples such as the Aztecs and Incas transformed the plant by selecting and breeding plants with mutations in their genetic structure, which resulted in desirable traits such as larger fruit [wanted characteristics]

6   We can now make a brand new species with wanted characteristics from scratch. [from nothing]

7   Taking the work further would be expensive because of the need to pay for a license for the CRISPR technology and get regulatory approval. [government acceptance] 

8   This approach could boost the use of many obscure plants, says Jonathan Jones of the Sainsbury Lab in the UK. [unfamiliar]

9   By choosing wild plants that are drought or heat tolerant, says Gao, we could create crops that will thrive even as the planet warms. [develop and grow]

**Comment by marcusgreen** [comment]
Thank you, I will investigate as soon as I can.

**Comment by marcusgreen** [comment]
Can you confirm what version of Moodle and the Plugin you are using. If you do an export of the question to xml and send/attach it here it will contain that information.

**Comment by bi1101** [comment]
[Simplify words.zip](https://github.com/marcusgreen/moodle-qtype_gapfill/files/9891580/Simplify.words.zip)
Here it is

**Comment by marcusgreen** [comment]
Thank you, looks like all recent versions so that simplifies things.

**Comment by marcusgreen** [comment]
I have uploaded your question to a test site and taken a quiz with it using and android phone. Can you attempt it yourself with the mobile app please.
Go to 
https://vledevelop.co.uk/gapfill/course/view.php?id=2
Login with  (not upper case P at the start of the password and ! at the end)
**username**
s1
**password**
Password1!

**Comment by bi1101** [comment]
Thank you I can confirm that the quiz behave as expected.

**Comment by bi1101** [comment]
Resolved. Error on the user's part
