### ISSUE TITLE
Display for student different that instructor

### ISSUE THREAD

**Issue by kzimme** [marcusgreen/moodle-qtype_gapfill#97]
Here is the code

<p dir="ltr" style="text-align: left;">Before attempting this question, think about taking a bite and following it through the process of digestion.<br><br>First, <strong>drag and drop </strong>the major organs on the left side of the graph, and then drag and drop the sections on the right
    side of the graph associated with the alimentary canal from beginning to end (do not include accessory organs).&nbsp; Some of the answers will not be used.&nbsp; <strong>Do not type in answers - Drag and Drop only.</strong></p>
<p dir="ltr" style="text-align: left;"></p>
<table border="3" cellpadding="3" cellspacing="3" width="244">

    <colgroup>
        <col width="119">
        <col width="125">
    </colgroup>
    <tbody>
        <tr height="20">
            <td height="20" width="119"><strong>Major Organ
            </strong></td>
            <td width="125"><strong>Sections</strong></td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;[<span><span style="">m</span><span style="">outh</span></span>]</td>
            <td>&nbsp;[lip]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[teeth and cheeks]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[tongue]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[palate]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[palatine tonsils]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;[<span><span>pharynx</span></span>]</td>
            <td>&nbsp;[nasopharynx]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[oropharynx]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[laryngopharynx]&nbsp;</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;[<span><span>esophagus</span></span>]</td>
            <td>&nbsp;[esophageal sphincter]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;[<span><span>stomach</span></span>]</td>
            <td>&nbsp;[cardiac]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[fundus]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[body]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[pyloris]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[pyloric sphincter]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;[<span><span>small intestines</span></span>]</td>
            <td>&nbsp;[duodenum]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[jejunum]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[ileum]&nbsp;</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[ileocecum sphincter]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;[<span><span>large intestines</span></span>]</td>
            <td>&nbsp;[cecum]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[vermiform appendix]</td>
        </tr>
        <tr height="20">
            <td height="20">&nbsp;blank</td>
            <td>&nbsp;[ascending colon]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[transverse colon]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[descending colon]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[sigmoid colon]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[rectum]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[involuntary sphincter]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[anus]</td>
        </tr>
        <tr height="20">
            <td height="20">blank</td>
            <td>&nbsp;[voluntary sphincter]</td>
        </tr>

    </tbody>
</table><br>
<p></p>

Instructor view looks correct but when students login the view is wrong.  Students only see the first column and the blanks are on the wrong side

**Additional context**

**Comment by marcusgreen** [comment]
I have just previewed it and it does look odd

**Comment by kzimme** [comment]
Do you have any idea why this is occurring ?  Instructor view is correct.

**Comment by marcusgreen** [comment]
There are some bits that will cause problems such as 
        <td height="20">&nbsp;[<span><span>small intestines</span></span>]</td>
The spans would mean there would probably be an issue interpreting. I have worked on creating the first few rows and copying and pasting the html down should allow you to get the whole set working.
<table border="1">
    <tbody>
        <tr>
            <td><strong>Major Organ</strong></td>
            <td><strong>Sections</strong></td>
        </tr>
        <tr>
            <td>[mouth]</td>
            <td>[lip]</td>
        </tr>
        <tr>
            <td>blank</td>
            <td>[teeth and cheeks]</td>
        </tr>
        <tr>
            <td>blank</td>
            <td>[tongue]</td>
        </tr>
        <tr>
            <td>blank</td>
            <td>[palate]</td>
        </tr>
        <tr>
            <td>[mouth]</td>
            <td>[palatine tonsils]</td>
        </tr>
        <tr>
            <td>[pharynx]</td>
            <td>[nasopharynx]</td>
        </tr>
        <tr>
            <td>blank</td>
            <td>[oropharynx]</td>
        </tr>
        <tr>
            <td>blank</td>
            <td>[laryngopharynx]</td>
        </tr>
        <tr>
            <td>[esophagus]</td>
            <td>[esophageal sphincter]</td>
        </tr>

    </tbody>
</table>

**Comment by marcusgreen** [comment]
[organs.txt](https://github.com/marcusgreen/moodle-qtype_gapfill/files/9933130/organs.txt)
